### ISSUE TITLE
As a user I want to be able to choose my location by clicking on a map so that choosing a location is easier/faster 

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#1]
### Acceptance criteria
**Given**
* The user is visiting the main page where a map is shown
  * Visiter of our website views the main page

**When**
* The user clicks on a country
  * The user clicks on Denmark

**Then**
* The country is highlighted to show that the country is chosen as location
  * Denmark is highlighted with a blueish color and the selected country is displayed with text below the map

**Happy case**
The country is successfully marked with a color and the country is chosen

**Bad case**
Nothing happens when the user clicks on a country and the selected country is not view below the map

### TASKS
- [x] (Asger - #12 ) Initial react setup and deploy
- [x] (Malte - #18 ) Header component, with links as specified by design. 
- [x] (Malte - #18 ) Footer component, with links as specified by design. 
- [x] (Asger - #13 ) Europe-view component with onclick on each country
- [x] (Asger - #14 ) Display the name of the chosen country below the Europe map

### Reference to design/prototype spike - https://github.com/Hold-Krykke/3SemProject_FrontEnd/issues/9

**Comment by MrHardcode** [comment]
Initial setup should be done now. We can manually deploy our frontend to <code>semholdkrykke.surge.sh</code> with the following command:

<code>surge --project ./build --domain semholdkrykke.surge.sh</code>

**Comment by MalteMagnussen** [comment]
We can start working on Footer and Header now? 
But zero styling, right?
Btw, what kinda Router are we using? I've only been able to get HashRouter to work on deployments.

![image](https://user-images.githubusercontent.com/11192971/69270232-d7378880-0bd2-11ea-805d-a6da42e3e076.png)

**Comment by MalteMagnussen** [comment]
Issue is done? Closing it for now.
