### ISSUE TITLE
As a user I want to be able to choose between the main cities in a given country, so I can specify which city I want to see Events in

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#2]
### Acceptance criteria
**Given** 
* Country is already chosen
  * User has clicked on Denmark

**When** 
* User chooses a city from a  map view (if this can't work then instead a list of ca 5 cities)

**Then** 
* Confirmation of selection
  * The user chooses a country from the map (or dropdown if the map can't be made) and the a pop-up datepicker appears.

**Happy case**
User has already chosen a country from a map view and chooses a city from the new map view (a dropdown). That city is then the selected value.

**Bad case**
A country has no cities
The city is not selected when clicked

### TASKS
(https://github.com/Hold-Krykke/3SemProject_FrontEnd/pull/28)
- [x] ~~Math/logic behind the svg (spike #19 ) and convert to code~~ not possible, will be hardcoded
  - [x] Manipulation of viewbox to show the chosen country and zoom ind (see svg science in discord)
- [x] Create labels from lat/long (will be hardcoded)
- [x] Button to confirm the chosen city

### IN CASE MAP CANT WORK
- [x] ~~Dropdown menu with 5 cities below the name of the chosen country~~

**Comment by MrHardcode** [comment]
This user story is definitely not small :P
