### ISSUE TITLE
As a user I want an intuitive design so that using the application is faster and more satisfying

### ISSUE THREAD

**Issue by MrHardcode** [Hold-Krykke/3SemProject_FrontEnd#21]
### Acceptance criteria
**Given** 
* User has loaded the main page of the application and sees a map of Europe.
  * The user has loaded the front page in their browser

**When**
* User clicks on a country and a zoomed in view of the chosen country is displayed with ca the five biggest cities shown on the map
  * The user clicks on Denmark and a zoomed in view of Denmark appears. On this view of Denmark, the five biggest cities in Denmark are shown

**Then** 
* User continues to the next view of the application
  * The user clicks on Århus. Århus is chosen and the user can now continue to the next view in the application

**Happy case**
- ~~The general design of the application is appealing. It has a blue theme~~
- The user can click through the application with easy
- The user doesn't have to write anything themselves and make sure to spell everything correctly - they can simply click their way through the application

**Bad case**
- ~~The application has no styling~~
- Nothing happens when the user clicks on a country
- After clicking a country, a new zoomed in view of the country appears but there a no cities to choose from on the map

### TASKS
- [x] Arrange outsourcing for some or all of the tasks below
- [x] Create a Country component to show a zoomed in view of the chosen country
- [x] Make sure the 5 biggest cities are shown on the country view
  - [x] Make sure the countries are placed correctly on the map
- [x] Make the 5 biggest countries clickable
- [x] Create a "back" button so that the user can return to the Europe map view
- [ ] ~~Create styling for the whole application~~

### Related Spikes
- spike https://github.com/Hold-Krykke/3SemProject_FrontEnd/issues/10
- ~~spike https://github.com/Hold-Krykke/3SemProject_FrontEnd/issues/19~~

**Comment by MrHardcode** [comment]
This User Story has already been implemented in other User Stories
