### ISSUE TITLE
As a user I want to be able to choose a date so that I can get upcoming events

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#3]
### Acceptance criteria
**Given**
* The user is visiting our website on the main page

**When**
* The user selects a date from a calendar

**Then**
* The date is selected and shown as chosen date and the calendar is closed/minimized
  * The date is selected and shown as chosen date

**Happy case**
The date is successfully chosen and the user can see that the date has been chosen

**Bad case**
The calendar doesn’t appear when you press choose date
The calendar appears but nothing happens when the user tries to choose a date
The user clicks on a date and the calendar is minimized but the date is not properly chosen

### TASKS
- [x] Pop-up (modal or alert) with onclick calendar, with functionality specified by Umers design
- [x] There needs to be sent 2 dates to the backend, they can be the same date
- [x] Fetch to getEvents endpoint
### RESOURCES
https://reactdatepicker.com/

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
https://bootsnipp.com/snippets/a6Kz3
https://react-bootstrap.github.io/components/modal/
