### ISSUE TITLE
As a user I want my application to be styled so that my webapp is more visually appealing

### ISSUE THREAD

**Issue by MrHardcode** [Hold-Krykke/3SemProject_FrontEnd#33]
### Acceptance criteria
**Given**
* User has loaded the main page of the webapp

**When**
* User sees the map view of Europe

**Then**
* User observes that the application is styled with a blue theme

**Happy case**
- The entire application is styled

**Bad case**
- Only some views in the application is styled
- The application has no styling

### TASKS
- [x] (Rúni) Outsource the styling
- [x] (Camilla - #40) When receiving the outsourced styling - make sure it works with our application
  - [x] Check all button-placements and move those that overlap 
  - [x] Style the `/about/` page.
     - Maybe take inspiration from the gradient in `header`
- [x] Update footer text from *lorem ipsum* to actual
  - [x] Investigate font for the `github-logo-text`
![image](https://user-images.githubusercontent.com/37186286/70374460-c2593580-18f2-11ea-8f67-c47f698c2b12.png)
- [x] Remove/Change gradient color in `header` - what do we want here? **`start over?`**?
- [x] Cleanup 

#### Result
  - [x] Add a `go back` button to the `Result` view
  - [x] On `Result`, change `eventName` to hold a link (`<a>`-tag) to ticketmaster. (`eventURL`)

#### DatePicker
- [x] Handle Date Ranges 
```md
https://github.com/ Hacker0x01 /react-datepicker/issues/584
``` 
(remove spaces, thx github)
- [x] `See events`-button
- [x] ~~`Today`-button (Maybe not that important, as we start selector on `new Date()`)~~

*Meget af koden der mangler kan hives ind fra tidligere branches-
Der er på nuværende master en fuld funktionel `back`-button på `Result` (med ekstra funktionalitet)
& de to **datepicker** knapper findes også.
Det eneste 'nye' er nok date ranges & styling af `about` samt af ovenstående knapper*
