### ISSUE TITLE
As a user I want to see a list of events, so that I can choose one to explore

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#4]
### Acceptance criteria
**Given**
* User has previously chosen a country, then a city from the map views
  *  User clicks country _Denmark_ and choses city _Copenhagen_

**When**
* System has made a call to retrieve data of events 
  *  System fetches data from one API, uses this data to fetch from a second API

**Then**
* System displays a list of events in requested city that can be read & interacted with by the user

**Happy case**
User gets a list of events, finds a relevant one and continues to it.

**Bad case**
The list is not returned (error)
The list is empty (no events - nothing we can do)
The event is wrong / its link reference does not work
The user does not find a relevant event (personal interest - nothing we can do)

### TASKS
- [x] (Runi - #24) Insides of overlying accordion/tab component, shows a list of links/buttons of events
  - [x] (Runi - #24) Shows a message if there's no events 
  - [x] (Runi - #24) Events should have title, location and date according to design
- [x] (Malte - #26 #22) Add back buttons/header breadcrumbs (to handle bad cases)

### RESOURCES
https://getbootstrap.com/docs/4.3/components/collapse/

Bootstrap-react:
https://react-bootstrap.github.io/components/accordion/

https://react-bootstrap.github.io/components/tabs/#tabs-controlled
https://react-bootstrap.github.io/components/cards/#navigation

### Details
Should be done using fetch info from #3. Use test data until then
