### ISSUE TITLE
As a user I want the application to be stable and it shouldn’t go down if I use it incorrectly 

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#5]
### Acceptance criteria
**Given**
* During browsing of the application

**When**
* Incorrect use of the application, i.e. click on water on map

**Then**
* An error message is shown with a good description of the error

**Happy case**
The user clicks on the ocean instead of a country and is shown an error message that tells him what he did wrong. 

**Bad case**
The user clicks on the ocean instead of a country and is not shown an error message that tells him what he did wrong. 

### TASKS
- [x] (Pair programming: Asger + himself) Tie together all components with correct use of state
- [x] (Camilla https://github.com/Hold-Krykke/3SemProject_FrontEnd/pull/45) Errormessage or no action or combination when unsupported places (ocean or a country we don't use) are clicked
- [x] (Rúni - https://github.com/Hold-Krykke/3SemProject_FrontEnd/pull/42/commits/855fcaa2e17489afd0290128a937e5544b0f58ab) Errormessage if user via url navigates to country or list-view without clicking a country and/or city
- [x] (Asger - #36) Fix date picker 
- [x] Bug Fixes - https://github.com/Hold-Krykke/3SemProject_BackEnd/issues/19 Amongst others. 

### RESOURCES
https://reactjs.org/docs/error-boundaries.html (see the live demo)
