### ISSUE TITLE
As a user I want to see clothing recommendations for a given city and date, so I know what to pack/wear

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#6]
### Acceptance criteria
**Given**
* User has chosen country, city and date

**When**
* When user has chosen the above

**Then**
* The user is shown the clothing recommendations 

**Happy case**
User is shown what clothes to wear

**Bad case**
User is not shown what clothes to wear

### TASKS
_Maybe do this as Pair Programming?_
- [ ] Frontend - Show the data in the result component in the proper tab
- [ ] Make the calls in the backend. Use TTD as described below. 
- [ ] Error handling in the backend
- [ ] Make error handling in the frontend 
- [ ] Clothing recommendation from Chokobananen. 
- [ ] If no date (= all future dates) or a date to far in the future is chosen, there should be a message about that instead. 

# Make sure to do this as Test Driven Development.
Make sure to get enough details from Benjamins group, so this is possible.
Make the calls in the backend. So that we can do Test Driven Development.
#### Remember to document what you're doing with regards to TTD here:
https://docs.google.com/document/d/1Y4kdCV2-WIFiFYfp97N-HVaoYIC_wz4LtbFvke--aOM/edit#heading=h.s10xy514l4ai

https://ajuhlhansen.dk/WeatherCloud/api/weather/city/(cityname)/(yyyy)/(MM)/(dd)
https://ajuhlhansen.dk/WeatherCloud/api/weather/city/(cityname)

**Comment by MalteMagnussen** [comment]
Buble

**Comment by MalteMagnussen** [comment]
Do it Test First

**Comment by MalteMagnussen** [comment]
So it turns out that "Clothing Recommendations" are "Funny Advice"

Example:
"funnyAdvice":"Is it snow? ... is it rain? ... no, it's hail, so keep your head down or you might turn blind!"

After talking with Runi, we no longer think this justifies it's own User Story or Tab in the GUI.

The data is sent along with the normal endpoints, so no reason to do separate TTD etc for that. 

Closing this issue for now.
