### ISSUE TITLE
As a user I want to know how the weather is in a given city so that I can decide which event to go to

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_FrontEnd#7]
# Acceptance criteria
**Given**
* The user has chosen a date

**When**
* The user chooses a location

**Then**
* The user gets a weather report based on date and location

**Happy case**
The user is shown the correct weather report 

**Bad case**
No weather report is shown
The wrong weather report is shown

### TASKS
_Maybe do this as Pair Programming?_
**FRONTEND**
- [x] (Asger - ~~#35~~) Change weather api useEffect to call on eventData and send it to component
  - Fixed in #43 
- [x] (Runi - #30 ) Frontend - Show the data in the result component in the proper tab
  - [x] (Runi - #30 ) When you onClick the tab for the Weather Component, ~~make a fetch call to the endpoint and~~(old way, Asger will refactor) populate the tab with: Weather, Funny Advice and use the icons. 
- [x] (Runi - #42 ) error handling and remaining fixes in the frontend 
- [x] (Runi - #37 ) Proper date handling on fetch calls
- [x] (Asger - ~~#35~~) Fix bug that occurs when opening weather tab multiple times - data is not overwritten but concatenated.
  - Fixed in #43 

**BACKEND**
- [x] Make the calls in the backend. Use TTD as described below. 
  - [x] (Malte [23](https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/23))Make the call to [Specific Date Endpoint](https://ajuhlhansen.dk/WeatherCloud/api/weather/city/Copenhagen/2017/10/04)
  - [x] (Malte [24](https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/24)) Make the call to 5 [days weather Endpoint](https://ajuhlhansen.dk/WeatherCloud/api/weather/city/Copenhagen)
  - [x] Maybe more endpoints as per documentation? ( make this task more detailed and split it ) 
- [x] Error handling in the backend 
  - [x] (Malte [23](https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/23)) Specific Date Endpoint
  - [x] (Malte [24](https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/24)) 5 days weather Endpoint
  - [x] Maybe more testing of edgecases as per documentation with their errormessages? ( make this task more detailed and split it ) 
- [x] **Document!!** *Link below*
# Issue
_If_ someone has selected more than one date, and there are multiple events across many dates, how should we show the events and weather in the GUI ? 

## Make sure to do this as Test Driven Development.
Make sure to get enough details from Benjamins group, so this is possible.
Make the calls in the backend. So that we can do Test Driven Development.
#### Remember to document what you're doing with regards to TTD here:
https://docs.google.com/document/d/1Y4kdCV2-WIFiFYfp97N-HVaoYIC_wz4LtbFvke--aOM/edit#heading=h.s10xy514l4ai

https://ajuhlhansen.dk/WeatherCloud/api/weather/city/(cityname)/(yyyy)/(MM)/(dd)
https://ajuhlhansen.dk/WeatherCloud/api/weather/city/(cityname)

**Comment by MalteMagnussen** [comment]
Buble

**Comment by MalteMagnussen** [comment]
Do it Test First

**Comment by MalteMagnussen** [comment]
Starting on this now.

**Comment by Runi-VN** [comment]
Paired with #6 due to there being 1 combined API instead of the expected 2

**Comment by Runi-VN** [comment]
As this was a bubble it was moved to sprint 3. For sprint 3 we have minor features, logic and bughandling changes, everything else is ready.

**Comment by Runi-VN** [comment]
Done when #42 is merged
